/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_honjane_handlerdemo_MainActivity */

#ifndef _Included_com_honjane_handlerdemo_MainActivity
#define _Included_com_honjane_handlerdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_honjane_handlerdemo_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_honjane_handlerdemo_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_honjane_handlerdemo_MainActivity_ThreadWithLooper */

#ifndef _Included_com_honjane_handlerdemo_MainActivity_ThreadWithLooper
#define _Included_com_honjane_handlerdemo_MainActivity_ThreadWithLooper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_honjane_handlerdemo_MainActivity_ThreadWithLooper_MIN_PRIORITY
#define com_honjane_handlerdemo_MainActivity_ThreadWithLooper_MIN_PRIORITY 1L
#undef com_honjane_handlerdemo_MainActivity_ThreadWithLooper_NORM_PRIORITY
#define com_honjane_handlerdemo_MainActivity_ThreadWithLooper_NORM_PRIORITY 5L
#undef com_honjane_handlerdemo_MainActivity_ThreadWithLooper_MAX_PRIORITY
#define com_honjane_handlerdemo_MainActivity_ThreadWithLooper_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_honjane_handlerdemo_MainActivity_Mythread */

#ifndef _Included_com_honjane_handlerdemo_MainActivity_Mythread
#define _Included_com_honjane_handlerdemo_MainActivity_Mythread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
